# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='departement',
            new_name='departement_code',
        ),
        migrations.AddField(
            model_name='location',
            name='departement_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='departement_nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='departement_nom_maj',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='departement_slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='departement_soundex',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
