# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('sector_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='hitarget.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('company_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='hitarget.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hitarget.Card')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('validating', 'En cours de validation'), ('offline', 'Inactif'), ('online', 'Actif'), ('expired', 'Expiré'), ('acquired', 'Déjà acquis')], default='validating', max_length=10, verbose_name='État')),
                ('expires_in', models.CharField(choices=[('1d', 'Un jour'), ('1w', 'Une semaine'), ('2w', 'Deux semaines'), ('1m', 'Un mois')], default='1w', max_length=2, verbose_name='Durée de validité')),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du lead')),
                ('description_short', models.TextField(verbose_name='Résumé du besoin')),
                ('maturity_level', models.CharField(choices=[('inform', 'Se renseigne'), ('eval', 'Évalue des opportunités'), ('search', "Cherche à s'équipper")], default='inform', max_length=10, verbose_name='Niveau de maturité')),
                ('date_expired', models.DateTimeField()),
                ('description_full', models.TextField(verbose_name='Description complète')),
                ('category', models.CharField(max_length=220, verbose_name='Les rubriques')),
                ('location', models.CharField(max_length=160, verbose_name='Lieu')),
                ('contact_name', models.CharField(max_length=120, verbose_name='Nom du contact')),
                ('contact_phone_number', models.CharField(max_length=120, verbose_name='Son téléphone')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Son email')),
                ('contact_company', models.CharField(max_length=120, verbose_name='La société')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Category', verbose_name='Rubriques liées')),
                ('contact_company_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Company', verbose_name='Société liée')),
                ('location_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Location', verbose_name='Lieux liés')),
            ],
            options={
                'ordering': ('-date_publish',),
            },
            bases=('hitarget.card',),
        ),
    ]
