# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='hitarget.Contact'),
        ),
    ]
