# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0002_lead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='maturity_level',
            field=models.CharField(choices=[('validating', 'En cours de validation'), ('offline', 'Inactif'), ('online', 'Actif'), ('expired', 'Expiré'), ('acquired', 'Déjà acquis')], default='validating', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inform', 'Se renseigne'), ('eval', 'Évalue des opportunités'), ('search', "Cherche à s'équipper")], default='inform', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date_publish'),
        ),
    ]
