# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0003_auto_20170207_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
