# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0004_auto_20170208_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='id',
        ),
        migrations.AddField(
            model_name='lead',
            name='card_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hitarget.Card'),
            preserve_default=False,
        ),
    ]
