# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0005_auto_20170220_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='maturity_level',
            field=models.CharField(choices=[('inform', 'Se renseigne'), ('eval', 'Évalue des opportunités'), ('search', "Cherche à s'équipper")], default='inform', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('validating', 'En cours de validation'), ('offline', 'Inactif'), ('online', 'Actif'), ('expired', 'Expiré'), ('acquired', 'Déjà acquis')], default='validating', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='hitarget.Location'),
        ),
    ]
