# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0007_auto_20170302_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='hitarget.Category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='hitarget.Company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='category_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_company_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Company'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Location'),
        ),
    ]
