# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0008_auto_20170302_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(max_length=220, verbose_name='Les rubriques'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Category', verbose_name='Rubriques liées'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_company',
            field=models.CharField(max_length=120, verbose_name='La société'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_company_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Company', verbose_name='Société liée'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Son email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(max_length=120, verbose_name='Nom du contact'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_phone_number',
            field=models.CharField(max_length=120, verbose_name='Son téléphone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description_full',
            field=models.TextField(verbose_name='Description complète'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description_short',
            field=models.TextField(verbose_name='Résumé du besoin'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='expires_in',
            field=models.CharField(choices=[('1d', 'Un jour'), ('1w', 'Une semaine'), ('2w', 'Deux semaines'), ('1m', 'Un mois')], default='1w', max_length=2, verbose_name='Durée de validité'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(max_length=160, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hitarget.Location', verbose_name='Lieux liés'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='maturity_level',
            field=models.CharField(choices=[('inform', 'Se renseigne'), ('eval', 'Évalue des opportunités'), ('search', "Cherche à s'équipper")], default='inform', max_length=10, verbose_name='Niveau de maturité'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('validating', 'En cours de validation'), ('offline', 'Inactif'), ('online', 'Actif'), ('expired', 'Expiré'), ('acquired', 'Déjà acquis')], default='validating', max_length=10, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titre du lead'),
        ),
    ]
