# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitarget', '0009_auto_20170306_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='account.Profile', verbose_name='Auteur'),
        ),
    ]
